name = "your-worker-name"
type = "javascript"
main = "worker-files/indexWorker.js"

account_id = "your-account-id"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = ["10 7 * * mon-fri"]

# [vars]
# APU_TIMETABLE_S3 = "INSERT VALUE HERE"
# INTAKE_CODE = "INSERT VALUE HERE"
# CALENDAR_ID = "INSERT VALUE HERE"
# PROJECT_ID = "INSERT VALUE HERE"
# PRIVATE_KEY_ID = "INSERT VALUE HERE"
# PRIVATE_KEY = "INSERT VALUE HERE"
# CLIENT_EMAIL = "INSERT VALUE HERE"
# CLIENT_ID = "INSERT VALUE HERE"
# CLIENT_CERT_URL = "INSERT VALUE HERE"
